- name: ensuring directories for {{ name }}
  file: path={{ item }} state=directory
  with_items: app_dirs

- name: installing config for {{ name }}
  template: src=app.ini.j2 dest={{ supervisor_home }}/conf.d/{{ name }}.ini
  register: supervisor_template

- name: rereading configs
  shell: '{{ supervisorctl_path }} -c {{ supervisor_config }} reread'
  when: supervisor_template|changed

- name: rereading configs
  shell: '{{ supervisorctl_path }} -c {{ supervisor_config }} update {{ name }}'
  when: supervisor_template|changed
