dependencies:
  - role: supervise
    name: etcd
    command: etcd -n {{ ansible_hostname }} -c {{ etcd_client_address }} -s {{ etcd_server_address }} -cl 0.0.0.0 -sl 0.0.0.0 {% if etcd_join_address %}-C {{ etcd_join_address }}{% endif %}
    autostart: off
