- name: installing deps
  hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: installing required system packages
      apt: pkg={{ item }} state=present
      with_items:
        - unzip
        - python-virtualenv
